package com.bplow.netconn.aom.dao.impl;

import java.sql.SQLException;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.bplow.netconn.aom.dao.TbServerHostDAO;
import com.bplow.netconn.aom.dao.entity.TbServerHost;
import com.bplow.netconn.aom.dao.entity.TbServerHostExample;
import com.ibatis.sqlmap.client.SqlMapClient;

@Service
public class TbServerHostDAOImpl implements TbServerHostDAO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
	@Autowired
    private SqlMapClient sqlMapClient;
	
    public TbServerHostDAOImpl() {
		super();
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public TbServerHostDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public int countByExample(TbServerHostExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("tb_server_host.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public int deleteByExample(TbServerHostExample example) throws SQLException {
        int rows = sqlMapClient.delete("tb_server_host.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public int deleteByPrimaryKey(String id) throws SQLException {
        TbServerHost _key = new TbServerHost();
        _key.setId(id);
        int rows = sqlMapClient.delete("tb_server_host.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public void insert(TbServerHost record) throws SQLException {
        sqlMapClient.insert("tb_server_host.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public void insertSelective(TbServerHost record) throws SQLException {
        sqlMapClient.insert("tb_server_host.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    @SuppressWarnings("unchecked")
    public List<TbServerHost> selectByExample(TbServerHostExample example) throws SQLException {
        List<TbServerHost> list = sqlMapClient.queryForList("tb_server_host.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public TbServerHost selectByPrimaryKey(String id) throws SQLException {
        TbServerHost _key = new TbServerHost();
        _key.setId(id);
        TbServerHost record = (TbServerHost) sqlMapClient.queryForObject("tb_server_host.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public int updateByExampleSelective(TbServerHost record, TbServerHostExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("tb_server_host.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public int updateByExample(TbServerHost record, TbServerHostExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("tb_server_host.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public int updateByPrimaryKeySelective(TbServerHost record) throws SQLException {
        int rows = sqlMapClient.update("tb_server_host.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public int updateByPrimaryKey(TbServerHost record) throws SQLException {
        int rows = sqlMapClient.update("tb_server_host.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    protected static class UpdateByExampleParms extends TbServerHostExample {
        private Object record;

        public UpdateByExampleParms(Object record, TbServerHostExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}