package com.bplow.netconn.systemmng.dao.entity;

// default package
// Generated 2015-11-29 9:44:02 by Hibernate Tools 3.6.0.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysMenu generated by hbm2java
 */
@Entity
@Table(name="sys_menu"
    ,catalog="ads"
)
public class SysMenu  implements java.io.Serializable {


     private Integer id;
     private String menuName;
     private String menuDesc;
     private String uri;
     private Date gmtCreate;
     private Date gmtModify;

    public SysMenu() {
    }

    public SysMenu(String menuName, String menuDesc, String uri, Date gmtCreate, Date gmtModify) {
       this.menuName = menuName;
       this.menuDesc = menuDesc;
       this.uri = uri;
       this.gmtCreate = gmtCreate;
       this.gmtModify = gmtModify;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="menu_name", nullable=false, length=100)
    public String getMenuName() {
        return this.menuName;
    }
    
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    
    @Column(name="menu_desc", nullable=false, length=100)
    public String getMenuDesc() {
        return this.menuDesc;
    }
    
    public void setMenuDesc(String menuDesc) {
        this.menuDesc = menuDesc;
    }

    
    @Column(name="uri", nullable=false, length=100)
    public String getUri() {
        return this.uri;
    }
    
    public void setUri(String uri) {
        this.uri = uri;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="gmt_create", nullable=false, length=19)
    public Date getGmtCreate() {
        return this.gmtCreate;
    }
    
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="gmt_modify", nullable=false, length=19)
    public Date getGmtModify() {
        return this.gmtModify;
    }
    
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }




}


