package com.bplow.netconn.systemmng.dao.entity;

import java.util.Date;

import com.bplow.netconn.base.dao.domain.PageImpl;
import com.fasterxml.jackson.annotation.JsonFormat;

public class SysOrganization extends PageImpl{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.id
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.organize_name
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    private String organizeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.organize_desc
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    private String organizeDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.status
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.gmt_create
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    @JsonFormat(locale="zh", timezone="GMT+8", pattern="yyyy-MM-dd HH:mm:ss")
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.gmt_modify
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    @JsonFormat(locale="zh", timezone="GMT+8", pattern="yyyy-MM-dd HH:mm:ss")
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.id
     *
     * @return the value of sys_organization.id
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.id
     *
     * @param id the value for sys_organization.id
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.organize_name
     *
     * @return the value of sys_organization.organize_name
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    public String getOrganizeName() {
        return organizeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.organize_name
     *
     * @param organizeName the value for sys_organization.organize_name
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    public void setOrganizeName(String organizeName) {
        this.organizeName = organizeName == null ? null : organizeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.organize_desc
     *
     * @return the value of sys_organization.organize_desc
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    public String getOrganizeDesc() {
        return organizeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.organize_desc
     *
     * @param organizeDesc the value for sys_organization.organize_desc
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    public void setOrganizeDesc(String organizeDesc) {
        this.organizeDesc = organizeDesc == null ? null : organizeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.status
     *
     * @return the value of sys_organization.status
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.status
     *
     * @param status the value for sys_organization.status
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.gmt_create
     *
     * @return the value of sys_organization.gmt_create
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.gmt_create
     *
     * @param gmtCreate the value for sys_organization.gmt_create
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.gmt_modify
     *
     * @return the value of sys_organization.gmt_modify
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.gmt_modify
     *
     * @param gmtModify the value for sys_organization.gmt_modify
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysOrganization other = (SysOrganization) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrganizeName() == null ? other.getOrganizeName() == null : this.getOrganizeName().equals(other.getOrganizeName()))
            && (this.getOrganizeDesc() == null ? other.getOrganizeDesc() == null : this.getOrganizeDesc().equals(other.getOrganizeDesc()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModify() == null ? other.getGmtModify() == null : this.getGmtModify().equals(other.getGmtModify()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrganizeName() == null) ? 0 : getOrganizeName().hashCode());
        result = prime * result + ((getOrganizeDesc() == null) ? 0 : getOrganizeDesc().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModify() == null) ? 0 : getGmtModify().hashCode());
        return result;
    }
}