package com.bplow.netconn.systemmng.dao.entity;

// default package
// Generated 2015-11-29 9:44:02 by Hibernate Tools 3.6.0.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysOrganization generated by hbm2java
 */
@Entity
@Table(name="sys_organization"
    ,catalog="ads"
)
public class SysOrganization  implements java.io.Serializable {


     private Integer id;
     private String organizeName;
     private String organizeDesc;
     private String status;
     private Date gmtCreate;
     private Date gmtModify;

    public SysOrganization() {
    }

    public SysOrganization(String organizeName, String organizeDesc, String status, Date gmtCreate, Date gmtModify) {
       this.organizeName = organizeName;
       this.organizeDesc = organizeDesc;
       this.status = status;
       this.gmtCreate = gmtCreate;
       this.gmtModify = gmtModify;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="organize_name", length=100)
    public String getOrganizeName() {
        return this.organizeName;
    }
    
    public void setOrganizeName(String organizeName) {
        this.organizeName = organizeName;
    }

    
    @Column(name="organize_desc", length=100)
    public String getOrganizeDesc() {
        return this.organizeDesc;
    }
    
    public void setOrganizeDesc(String organizeDesc) {
        this.organizeDesc = organizeDesc;
    }

    
    @Column(name="status", length=2)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="gmt_create", length=19)
    public Date getGmtCreate() {
        return this.gmtCreate;
    }
    
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="gmt_modify", length=19)
    public Date getGmtModify() {
        return this.gmtModify;
    }
    
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }




}


