package com.bplow.netconn.systemmng.dao.entity;

public class SysOrganizeUserRel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organize_user_rel.id
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organize_user_rel.user_id
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organize_user_rel.organize_id
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    private String organizeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organize_user_rel.id
     *
     * @return the value of sys_organize_user_rel.id
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organize_user_rel.id
     *
     * @param id the value for sys_organize_user_rel.id
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organize_user_rel.user_id
     *
     * @return the value of sys_organize_user_rel.user_id
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organize_user_rel.user_id
     *
     * @param userId the value for sys_organize_user_rel.user_id
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organize_user_rel.organize_id
     *
     * @return the value of sys_organize_user_rel.organize_id
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    public String getOrganizeId() {
        return organizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organize_user_rel.organize_id
     *
     * @param organizeId the value for sys_organize_user_rel.organize_id
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    public void setOrganizeId(String organizeId) {
        this.organizeId = organizeId == null ? null : organizeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysOrganizeUserRel other = (SysOrganizeUserRel) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getOrganizeId() == null ? other.getOrganizeId() == null : this.getOrganizeId().equals(other.getOrganizeId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getOrganizeId() == null) ? 0 : getOrganizeId().hashCode());
        return result;
    }
}