package com.bplow.netconn.systemmng.dao.entity;

// default package
// Generated 2015-11-29 9:44:02 by Hibernate Tools 3.6.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysRoleMenuRel generated by hbm2java
 */
@Entity
@Table(name="sys_role_menu_rel"
    ,catalog="ads"
)
public class SysRoleMenuRel  implements java.io.Serializable {


     private long id;
     private String roleId;
     private String menuId;

    public SysRoleMenuRel() {
    }

	
    public SysRoleMenuRel(long id) {
        this.id = id;
    }
    public SysRoleMenuRel(long id, String roleId, String menuId) {
       this.id = id;
       this.roleId = roleId;
       this.menuId = menuId;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="role_id", length=32)
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    
    @Column(name="menu_id", length=32)
    public String getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }




}


