package com.bplow.netconn.systemmng.dao.entity;

// default package
// Generated 2015-11-29 9:44:02 by Hibernate Tools 3.6.0.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysRole generated by hbm2java
 */
@Entity
@Table(name="sys_role"
    ,catalog="ads"
)
public class SysRole  implements java.io.Serializable {


     private Long 角色编号;
     private String 角色名称;
     private String 角色描述;
     private String 角色类别;
     private Date gmtCreate;
     private Date gmtModify;
     private Character status;

    public SysRole() {
    }

	
    public SysRole(Date gmtCreate, Date gmtModify) {
        this.gmtCreate = gmtCreate;
        this.gmtModify = gmtModify;
    }
    public SysRole(String 角色名称, String 角色描述, String 角色类别, Date gmtCreate, Date gmtModify, Character status) {
       this.角色名称 = 角色名称;
       this.角色描述 = 角色描述;
       this.角色类别 = 角色类别;
       this.gmtCreate = gmtCreate;
       this.gmtModify = gmtModify;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="角色编号", unique=true, nullable=false)
    public Long get角色编号() {
        return this.角色编号;
    }
    
    public void set角色编号(Long 角色编号) {
        this.角色编号 = 角色编号;
    }

    
    @Column(name="角色名称", length=100)
    public String get角色名称() {
        return this.角色名称;
    }
    
    public void set角色名称(String 角色名称) {
        this.角色名称 = 角色名称;
    }

    
    @Column(name="角色描述", length=100)
    public String get角色描述() {
        return this.角色描述;
    }
    
    public void set角色描述(String 角色描述) {
        this.角色描述 = 角色描述;
    }

    
    @Column(name="角色类别", length=2)
    public String get角色类别() {
        return this.角色类别;
    }
    
    public void set角色类别(String 角色类别) {
        this.角色类别 = 角色类别;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="gmt_create", nullable=false, length=19)
    public Date getGmtCreate() {
        return this.gmtCreate;
    }
    
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="gmt_modify", nullable=false, length=19)
    public Date getGmtModify() {
        return this.gmtModify;
    }
    
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    
    @Column(name="status", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }




}


