package com.bplow.netconn.systemmng.dao.entity;

public class SysRoleMenuRel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu_rel.id
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu_rel.role_id
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu_rel.menu_id
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    private String menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu_rel.id
     *
     * @return the value of sys_role_menu_rel.id
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu_rel.id
     *
     * @param id the value for sys_role_menu_rel.id
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu_rel.role_id
     *
     * @return the value of sys_role_menu_rel.role_id
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu_rel.role_id
     *
     * @param roleId the value for sys_role_menu_rel.role_id
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu_rel.menu_id
     *
     * @return the value of sys_role_menu_rel.menu_id
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu_rel.menu_id
     *
     * @param menuId the value for sys_role_menu_rel.menu_id
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysRoleMenuRel other = (SysRoleMenuRel) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
            && (this.getMenuId() == null ? other.getMenuId() == null : this.getMenuId().equals(other.getMenuId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbggenerated Sun May 08 15:10:04 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getMenuId() == null) ? 0 : getMenuId().hashCode());
        return result;
    }
}