package com.bplow.netconn.systemmng.dao.impl;

import com.bplow.netconn.systemmng.dao.SysMenuDAO;
import com.bplow.netconn.systemmng.dao.entity.SysMenu;
import com.bplow.netconn.systemmng.dao.entity.SysMenuExample;
import com.ibatis.sqlmap.client.SqlMapClient;

import java.sql.SQLException;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component("sysMenuDAOImpl")
public class SysMenuDAOImpl implements SysMenuDAO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_menu
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
	@Autowired
    private SqlMapClient sqlMapClient;

    public SysMenuDAOImpl() {
		super();
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    public SysMenuDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    public int countByExample(SysMenuExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("sys_menu.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    public int deleteByExample(SysMenuExample example) throws SQLException {
        int rows = sqlMapClient.delete("sys_menu.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    public int deleteByPrimaryKey(String id) throws SQLException {
        SysMenu _key = new SysMenu();
        _key.setId(id);
        int rows = sqlMapClient.delete("sys_menu.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    public void insert(SysMenu record) throws SQLException {
        sqlMapClient.insert("sys_menu.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    public void insertSelective(SysMenu record) throws SQLException {
        sqlMapClient.insert("sys_menu.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    @SuppressWarnings("unchecked")
    public List<SysMenu> selectByExample(SysMenuExample example) throws SQLException {
        List<SysMenu> list = sqlMapClient.queryForList("sys_menu.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    public SysMenu selectByPrimaryKey(String id) throws SQLException {
        SysMenu _key = new SysMenu();
        _key.setId(id);
        SysMenu record = (SysMenu) sqlMapClient.queryForObject("sys_menu.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    public int updateByExampleSelective(SysMenu record, SysMenuExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("sys_menu.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    public int updateByExample(SysMenu record, SysMenuExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("sys_menu.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    public int updateByPrimaryKeySelective(SysMenu record) throws SQLException {
        int rows = sqlMapClient.update("sys_menu.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    public int updateByPrimaryKey(SysMenu record) throws SQLException {
        int rows = sqlMapClient.update("sys_menu.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_menu
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    protected static class UpdateByExampleParms extends SysMenuExample {
        private Object record;

        public UpdateByExampleParms(Object record, SysMenuExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}