package com.bplow.netconn.systemmng.dao.impl;

import com.bplow.netconn.base.dao.BaseIbatisDaoSupport;
import com.bplow.netconn.base.dao.pagination.IPagination;
import com.bplow.netconn.systemmng.dao.SysOrganizationDAO;
import com.bplow.netconn.systemmng.dao.entity.SysOrganization;
import com.bplow.netconn.systemmng.dao.entity.SysOrganizationExample;
import com.fasterxml.jackson.core.JsonGenerationException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.ibatis.sqlmap.client.SqlMapClient;

import java.io.IOException;
import java.sql.SQLException;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component("sysOrganizationDAOImpl")
public class SysOrganizationDAOImpl extends BaseIbatisDaoSupport implements SysOrganizationDAO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_organization
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
	@Autowired
    private SqlMapClient sqlMapClient;

    public SysOrganizationDAOImpl() {
		super();
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    public SysOrganizationDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    public int countByExample(SysOrganizationExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("sys_organization.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    public int deleteByExample(SysOrganizationExample example) throws SQLException {
        int rows = sqlMapClient.delete("sys_organization.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        SysOrganization _key = new SysOrganization();
        _key.setId(id);
        int rows = sqlMapClient.delete("sys_organization.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    public void insert(SysOrganization record) throws SQLException {
        sqlMapClient.insert("sys_organization.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    public void insertSelective(SysOrganization record) throws SQLException {
        sqlMapClient.insert("sys_organization.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    @SuppressWarnings("unchecked")
    public List<SysOrganization> selectByExample(SysOrganizationExample example) throws SQLException {
        List<SysOrganization> list = sqlMapClient.queryForList("sys_organization.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    public SysOrganization selectByPrimaryKey(Integer id) throws SQLException {
        SysOrganization _key = new SysOrganization();
        _key.setId(id);
        SysOrganization record = (SysOrganization) sqlMapClient.queryForObject("sys_organization.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    public int updateByExampleSelective(SysOrganization record, SysOrganizationExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("sys_organization.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    public int updateByExample(SysOrganization record, SysOrganizationExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("sys_organization.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    public int updateByPrimaryKeySelective(SysOrganization record) throws SQLException {
        int rows = sqlMapClient.update("sys_organization.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    public int updateByPrimaryKey(SysOrganization record) throws SQLException {
        int rows = sqlMapClient.update("sys_organization.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_organization
     *
     * @mbggenerated Sun May 08 15:13:44 CST 2016
     */
    protected static class UpdateByExampleParms extends SysOrganizationExample {
        private Object record;

        public UpdateByExampleParms(Object record, SysOrganizationExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	/* (non-Javadoc)
	 * @see com.bplow.netconn.systemmng.dao.SysOrganizationDAO#queryOrgPage(com.bplow.netconn.systemmng.dao.entity.SysOrganization)
	 */
	@Override
	public IPagination queryOrgPage(SysOrganization record) throws Exception {
		
		IPagination pagination = this.queryForPagenation("sys_organization.selectCount", "sys_organization.selectList", record);
		
		return pagination;
	}
}