package com.bplow.netconn.systemmng.dao.impl;

import com.bplow.netconn.systemmng.dao.SysOrganizeUserRelDAO;
import com.bplow.netconn.systemmng.dao.entity.SysOrganizeUserRel;
import com.bplow.netconn.systemmng.dao.entity.SysOrganizeUserRelExample;
import com.ibatis.sqlmap.client.SqlMapClient;

import java.sql.SQLException;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component("sysOrganizeUserRelDAOImpl")
public class SysOrganizeUserRelDAOImpl implements SysOrganizeUserRelDAO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
	@Autowired
    private SqlMapClient sqlMapClient;

    public SysOrganizeUserRelDAOImpl() {
		super();
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    public SysOrganizeUserRelDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    public int countByExample(SysOrganizeUserRelExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("sys_organize_user_rel.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    public int deleteByExample(SysOrganizeUserRelExample example) throws SQLException {
        int rows = sqlMapClient.delete("sys_organize_user_rel.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    public int deleteByUserId(String userId) throws SQLException {
        SysOrganizeUserRel _key = new SysOrganizeUserRel();
        _key.setUserId(userId);
        int rows = sqlMapClient.delete("sys_organize_user_rel.deleteByPrimaryKey", _key);
        return rows;
    }
    
    public int deleteByOrgId(String organizeId) throws SQLException {
        SysOrganizeUserRel _key = new SysOrganizeUserRel();
        _key.setOrganizeId(organizeId);
        int rows = sqlMapClient.delete("sys_organize_user_rel.deleteByOrgId", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    public void insert(SysOrganizeUserRel record) throws SQLException {
        sqlMapClient.insert("sys_organize_user_rel.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    public void insertSelective(SysOrganizeUserRel record) throws SQLException {
        sqlMapClient.insert("sys_organize_user_rel.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    @SuppressWarnings("unchecked")
    public List<SysOrganizeUserRel> selectByExample(SysOrganizeUserRelExample example) throws SQLException {
        List<SysOrganizeUserRel> list = sqlMapClient.queryForList("sys_organize_user_rel.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    public SysOrganizeUserRel selectByPrimaryKey(Integer id) throws SQLException {
        SysOrganizeUserRel _key = new SysOrganizeUserRel();
        _key.setId(id);
        SysOrganizeUserRel record = (SysOrganizeUserRel) sqlMapClient.queryForObject("sys_organize_user_rel.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    public int updateByExampleSelective(SysOrganizeUserRel record, SysOrganizeUserRelExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("sys_organize_user_rel.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    public int updateByExample(SysOrganizeUserRel record, SysOrganizeUserRelExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("sys_organize_user_rel.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    public int updateByPrimaryKeySelective(SysOrganizeUserRel record) throws SQLException {
        int rows = sqlMapClient.update("sys_organize_user_rel.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    public int updateByPrimaryKey(SysOrganizeUserRel record) throws SQLException {
        int rows = sqlMapClient.update("sys_organize_user_rel.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    protected static class UpdateByExampleParms extends SysOrganizeUserRelExample {
        private Object record;

        public UpdateByExampleParms(Object record, SysOrganizeUserRelExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}