package com.bplow.netconn.systemmng.dao.impl;

import com.bplow.netconn.systemmng.dao.SysRoleDAO;
import com.bplow.netconn.systemmng.dao.entity.SysRole;
import com.bplow.netconn.systemmng.dao.entity.SysRoleExample;
import com.ibatis.sqlmap.client.SqlMapClient;

import java.sql.SQLException;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component("sysRoleDAOImpl")
public class SysRoleDAOImpl implements SysRoleDAO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_role
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
	@Autowired
    private SqlMapClient sqlMapClient;
	
    public SysRoleDAOImpl() {
		super();
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    public SysRoleDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    public int countByExample(SysRoleExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("sys_role.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    public int deleteByExample(SysRoleExample example) throws SQLException {
        int rows = sqlMapClient.delete("sys_role.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    public int deleteByPrimaryKey(String roleId) throws SQLException {
        SysRole _key = new SysRole();
        _key.setRoleId(roleId);
        int rows = sqlMapClient.delete("sys_role.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    public void insert(SysRole record) throws SQLException {
        sqlMapClient.insert("sys_role.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    public void insertSelective(SysRole record) throws SQLException {
        sqlMapClient.insert("sys_role.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    @SuppressWarnings("unchecked")
    public List<SysRole> selectByExample(SysRoleExample example) throws SQLException {
        List<SysRole> list = sqlMapClient.queryForList("sys_role.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    public SysRole selectByPrimaryKey(String roleId) throws SQLException {
        SysRole _key = new SysRole();
        _key.setRoleId(roleId);
        SysRole record = (SysRole) sqlMapClient.queryForObject("sys_role.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    public int updateByExampleSelective(SysRole record, SysRoleExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("sys_role.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    public int updateByExample(SysRole record, SysRoleExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("sys_role.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    public int updateByPrimaryKeySelective(SysRole record) throws SQLException {
        int rows = sqlMapClient.update("sys_role.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    public int updateByPrimaryKey(SysRole record) throws SQLException {
        int rows = sqlMapClient.update("sys_role.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_role
     *
     * @mbggenerated Sun May 08 15:13:45 CST 2016
     */
    protected static class UpdateByExampleParms extends SysRoleExample {
        private Object record;

        public UpdateByExampleParms(Object record, SysRoleExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}