package com.bplow.netconn.aom.dao;


import java.sql.SQLException;
import java.util.List;

import com.bplow.netconn.aom.dao.entity.TbServerHost;
import com.bplow.netconn.aom.dao.entity.TbServerHostExample;

public interface TbServerHostDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    int countByExample(TbServerHostExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    int deleteByExample(TbServerHostExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    int deleteByPrimaryKey(String id) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    void insert(TbServerHost record) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    void insertSelective(TbServerHost record) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    List<TbServerHost> selectByExample(TbServerHostExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    TbServerHost selectByPrimaryKey(String id) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    int updateByExampleSelective(TbServerHost record, TbServerHostExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    int updateByExample(TbServerHost record, TbServerHostExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    int updateByPrimaryKeySelective(TbServerHost record) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    int updateByPrimaryKey(TbServerHost record) throws SQLException;
}