package com.bplow.netconn.aom.dao.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class TbServerHost {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_server_host.id
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_server_host.host_name
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    private String hostName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_server_host.host_ip
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    private String hostIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_server_host.host_port
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    private String hostPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_server_host.user_name
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_server_host.user_pwd
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    private String userPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_server_host.host_status
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    private String hostStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_server_host.gmt_create
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    @JsonFormat(locale="zh", timezone="GMT+8", pattern="yyyy-MM-dd HH:mm:ss")
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_server_host.gmt_modify
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    @JsonFormat(locale="zh", timezone="GMT+8", pattern="yyyy-MM-dd HH:mm:ss")
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_server_host.id
     *
     * @return the value of tb_server_host.id
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_server_host.id
     *
     * @param id the value for tb_server_host.id
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_server_host.host_name
     *
     * @return the value of tb_server_host.host_name
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public String getHostName() {
        return hostName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_server_host.host_name
     *
     * @param hostName the value for tb_server_host.host_name
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public void setHostName(String hostName) {
        this.hostName = hostName == null ? null : hostName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_server_host.host_ip
     *
     * @return the value of tb_server_host.host_ip
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public String getHostIp() {
        return hostIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_server_host.host_ip
     *
     * @param hostIp the value for tb_server_host.host_ip
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public void setHostIp(String hostIp) {
        this.hostIp = hostIp == null ? null : hostIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_server_host.host_port
     *
     * @return the value of tb_server_host.host_port
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public String getHostPort() {
        return hostPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_server_host.host_port
     *
     * @param hostPort the value for tb_server_host.host_port
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public void setHostPort(String hostPort) {
        this.hostPort = hostPort == null ? null : hostPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_server_host.user_name
     *
     * @return the value of tb_server_host.user_name
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_server_host.user_name
     *
     * @param userName the value for tb_server_host.user_name
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_server_host.user_pwd
     *
     * @return the value of tb_server_host.user_pwd
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_server_host.user_pwd
     *
     * @param userPwd the value for tb_server_host.user_pwd
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_server_host.host_status
     *
     * @return the value of tb_server_host.host_status
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public String getHostStatus() {
        return hostStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_server_host.host_status
     *
     * @param hostStatus the value for tb_server_host.host_status
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public void setHostStatus(String hostStatus) {
        this.hostStatus = hostStatus == null ? null : hostStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_server_host.gmt_create
     *
     * @return the value of tb_server_host.gmt_create
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_server_host.gmt_create
     *
     * @param gmtCreate the value for tb_server_host.gmt_create
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_server_host.gmt_modify
     *
     * @return the value of tb_server_host.gmt_modify
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_server_host.gmt_modify
     *
     * @param gmtModify the value for tb_server_host.gmt_modify
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TbServerHost other = (TbServerHost) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getHostName() == null ? other.getHostName() == null : this.getHostName().equals(other.getHostName()))
            && (this.getHostIp() == null ? other.getHostIp() == null : this.getHostIp().equals(other.getHostIp()))
            && (this.getHostPort() == null ? other.getHostPort() == null : this.getHostPort().equals(other.getHostPort()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getUserPwd() == null ? other.getUserPwd() == null : this.getUserPwd().equals(other.getUserPwd()))
            && (this.getHostStatus() == null ? other.getHostStatus() == null : this.getHostStatus().equals(other.getHostStatus()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModify() == null ? other.getGmtModify() == null : this.getGmtModify().equals(other.getGmtModify()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_server_host
     *
     * @mbggenerated Sat Apr 23 12:36:53 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getHostName() == null) ? 0 : getHostName().hashCode());
        result = prime * result + ((getHostIp() == null) ? 0 : getHostIp().hashCode());
        result = prime * result + ((getHostPort() == null) ? 0 : getHostPort().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getUserPwd() == null) ? 0 : getUserPwd().hashCode());
        result = prime * result + ((getHostStatus() == null) ? 0 : getHostStatus().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModify() == null) ? 0 : getGmtModify().hashCode());
        return result;
    }
}