package com.bplow.netconn.newcms.dao;

// default package
// Generated 2015-7-12 12:19:33 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FmProduct generated by hbm2java
 */
public class FmProduct implements java.io.Serializable {

	private Long productId;
	private String productName;
	private String catalogId;
	private String productDesc;
	private String productImageUrl;
	private Character isShow;
	private Integer orderId;
	private Date gmtCreate;
	private Date gmtModify;

	public FmProduct() {
	}

	public FmProduct(String productName, String catalogId, String productDesc,
			String productImageUrl, Character isShow, Integer orderId,
			Date gmtCreate, Date gmtModify) {
		this.productName = productName;
		this.catalogId = catalogId;
		this.productDesc = productDesc;
		this.productImageUrl = productImageUrl;
		this.isShow = isShow;
		this.orderId = orderId;
		this.gmtCreate = gmtCreate;
		this.gmtModify = gmtModify;
	}

	public Long getProductId() {
		return this.productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getCatalogId() {
		return this.catalogId;
	}

	public void setCatalogId(String catalogId) {
		this.catalogId = catalogId;
	}

	public String getProductDesc() {
		return this.productDesc;
	}

	public void setProductDesc(String productDesc) {
		this.productDesc = productDesc;
	}

	public String getProductImageUrl() {
		return this.productImageUrl;
	}

	public void setProductImageUrl(String productImageUrl) {
		this.productImageUrl = productImageUrl;
	}

	public Character getIsShow() {
		return this.isShow;
	}

	public void setIsShow(Character isShow) {
		this.isShow = isShow;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Date getGmtCreate() {
		return this.gmtCreate;
	}

	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	public Date getGmtModify() {
		return this.gmtModify;
	}

	public void setGmtModify(Date gmtModify) {
		this.gmtModify = gmtModify;
	}

}
