package com.bplow.netconn.systemmng.dao;

import com.bplow.netconn.systemmng.dao.entity.SysMenu;
import com.bplow.netconn.systemmng.dao.entity.SysMenuExample;
import java.sql.SQLException;
import java.util.List;

public interface SysMenuDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int countByExample(SysMenuExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int deleteByExample(SysMenuExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int deleteByPrimaryKey(String id) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    void insert(SysMenu record) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    void insertSelective(SysMenu record) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    List<SysMenu> selectByExample(SysMenuExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    SysMenu selectByPrimaryKey(String id) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int updateByExampleSelective(SysMenu record, SysMenuExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int updateByExample(SysMenu record, SysMenuExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int updateByPrimaryKeySelective(SysMenu record) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int updateByPrimaryKey(SysMenu record) throws SQLException;
}