package com.bplow.netconn.systemmng.dao;

import com.bplow.netconn.systemmng.dao.entity.SysOrganizeUserRel;
import com.bplow.netconn.systemmng.dao.entity.SysOrganizeUserRelExample;
import java.sql.SQLException;
import java.util.List;

public interface SysOrganizeUserRelDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int countByExample(SysOrganizeUserRelExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int deleteByExample(SysOrganizeUserRelExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    void insert(SysOrganizeUserRel record) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    void insertSelective(SysOrganizeUserRel record) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    List<SysOrganizeUserRel> selectByExample(SysOrganizeUserRelExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    SysOrganizeUserRel selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int updateByExampleSelective(SysOrganizeUserRel record, SysOrganizeUserRelExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int updateByExample(SysOrganizeUserRel record, SysOrganizeUserRelExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int updateByPrimaryKeySelective(SysOrganizeUserRel record) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organize_user_rel
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int updateByPrimaryKey(SysOrganizeUserRel record) throws SQLException;
}