package com.bplow.netconn.systemmng.dao;

import com.bplow.netconn.systemmng.dao.entity.SysRole;
import com.bplow.netconn.systemmng.dao.entity.SysRoleExample;
import java.sql.SQLException;
import java.util.List;

public interface SysRoleDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int countByExample(SysRoleExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int deleteByExample(SysRoleExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int deleteByPrimaryKey(String roleId) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    void insert(SysRole record) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    void insertSelective(SysRole record) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    List<SysRole> selectByExample(SysRoleExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    SysRole selectByPrimaryKey(String roleId) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int updateByExampleSelective(SysRole record, SysRoleExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int updateByExample(SysRole record, SysRoleExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int updateByPrimaryKeySelective(SysRole record) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int updateByPrimaryKey(SysRole record) throws SQLException;
}