package com.bplow.netconn.systemmng.dao;

import com.bplow.netconn.systemmng.dao.entity.SysRoleMenuRel;
import com.bplow.netconn.systemmng.dao.entity.SysRoleMenuRelExample;
import java.sql.SQLException;
import java.util.List;

public interface SysRoleMenuRelDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int countByExample(SysRoleMenuRelExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int deleteByExample(SysRoleMenuRelExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int deleteByPrimaryKey(Long id) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    void insert(SysRoleMenuRel record) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    void insertSelective(SysRoleMenuRel record) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    List<SysRoleMenuRel> selectByExample(SysRoleMenuRelExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    SysRoleMenuRel selectByPrimaryKey(Long id) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int updateByExampleSelective(SysRoleMenuRel record, SysRoleMenuRelExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int updateByExample(SysRoleMenuRel record, SysRoleMenuRelExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int updateByPrimaryKeySelective(SysRoleMenuRel record) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbggenerated Sun May 08 15:12:46 CST 2016
     */
    int updateByPrimaryKey(SysRoleMenuRel record) throws SQLException;
}